// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo6LfwejgOmPcg6n1cTSj4lwj22PLI_40',
    appId: '1:423734160459:web:80559f817a1f6c5a22f1ce',
    messagingSenderId: '423734160459',
    projectId: 'medhack-fb93b',
    authDomain: 'medhack-fb93b.firebaseapp.com',
    storageBucket: 'medhack-fb93b.appspot.com',
    measurementId: 'G-4MXXK19RDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV0m1QezKgduAKFhKQuTekoQtbLA-lrME',
    appId: '1:423734160459:android:c1735e42629ecc6622f1ce',
    messagingSenderId: '423734160459',
    projectId: 'medhack-fb93b',
    storageBucket: 'medhack-fb93b.appspot.com',
  );
}
